[project]
name = "era-pl-templates"
version = "0.1.1"
description = "Runnable Quarto templates for Empirical Research in Accounting"
requires-python = ">=3.11,<3.14"
dependencies = [
    "db2pq>=0.2.2",
    "era-py[polars,tables]>=0.0.19",
    "ipykernel",
    "jupyter",
    "plotnine",
    "polars",
    "pyfixest>=0.40.1",
    "python-dotenv",
    "requests",
]
