[project]
name = "era-pl-templates"
version = "0.1.5"
description = "Runnable Quarto templates for Empirical Research in Accounting"
requires-python = ">=3.11,<3.14"
dependencies = [
    "altair>=6.0.0",
    "causalml>=0.15.5",
    "db2pq>=0.3.0",
    "era-py[polars,tables]>=0.0.30",
    "great-tables",
    "imbalanced-learn>=0.14.1",
    "ipykernel",
    "jupyter",
    "jupyter-cache",
    "linearmodels",
    "maketables>=0.1.8",
    "matplotlib",
    "numpy",
    "pandas",
    "pdfplumber",
    "plotnine",
    "plotnine-polars>=0.2.0",
    "polars[excel]>=1.39.3",
    "pyfixest>=0.40.1",
    "python-dotenv",
    "quarto",
    "rdrobust>=1.3.0",
    "requests",
    "scikit-learn>=1.8.0",
    "scipy",
    "seaborn",
    "statsmodels",
]
